Creating Arays

In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9])

arr2 = np.array([[1,2,3],[4,5,6]])

print("1D Array :",arr1)
print("2D Array:\n",arr2)

1D Array : [1 2 3 4 5 6 7 8 9]
2D Array:
 [[1 2 3]
 [4 5 6]]


1.1.Arithematic operations

In [4]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print("Addition",a+b)
print("Substraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)


Addition [11 22 33 44]
Substraction [ 9 18 27 36]
Multiplication [ 10  40  90 160]
Division [10. 10. 10. 10.]


1.2.Scalar Operations

In [5]:
print("a*2",a*2)
print("a+5",a+5)

a*2 [20 40 60 80]
a+5 [15 25 35 45]


3.Mathematical Functions

In [6]:
arr = np.array([1,2,3,4,5])

print("Square root",np.sqrt(arr))
print("Exponential",np.exp(arr))
print("Sine",np.sin(arr))
print("Logarithm",np.log(arr))

Square root [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Logarithm [0.         0.69314718 1.09861229 1.38629436 1.60943791]


4.Aggregate Functions

In [7]:
arr = np.array([10,20,30,40,50])
print("Sum",np.sum(arr))
print("Mean",np.mean(arr))
print("Max",np.max(arr))
print("Min",np.min(arr))
print("Standard Deviation",np.std(arr))

Sum 150
Mean 30.0
Max 50
Min 10
Standard Deviation 14.142135623730951


5.Matrix Operations

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix Addition:\n",A+B)
print("Matrix Multiplication:\n",np.dot(A,B))
print("Transpose:\n",A.T)

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]


6.Indexing and Slicing

In [11]:
arr = np.array([10,20,30,40,50])

print("Element in the index 2:",arr[2])
print("First three elements:",arr[:3])
print("Last two elements:",arr[-2:])

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Element(2,1):",arr2[1,2])
print("First row",arr2[1,2])
print("First column:",arr2[:,0])



Element in the index 2: 30
First three elements: [10 20 30]
Last two elements: [40 50]
Element(2,1): 6
First row 6
First column: [1 4 7]
